version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - mvn test
      - mvn package
      - mv target/spring-boot-aws-beanstalk-0.0.2-SNAPSHOT.war ROOT.war
artifacts:
  files:
    - ROOT.war
    - .ebextensions/**/*